# Generated by Django 3.1.1 on 2020-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Máximum of 30 Characters', max_length=30, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Máximum of 100 Characters', max_length=100, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
            ],
        ),
    ]
